config/routes.rb
Voc::Application.routes.draw do
  
  devise_for :users
  get 'users/profile' => 'users#profile'
  match 'users/save_selections' => 'users#save_selections', via: [:post]

  root 'words#index'

  
  match 'words' => 'words#index', via: [:get, :post]
  match 'words/save_selection' => 'words#save_selection', via: [:post]
  
  match 'tests' => 'tests#index', via: [:post]
  match 'tests/autosave' => 'tests#autosave', via: [:post]
  get 'tests/autoload' => 'tests#autoload'
  match 'tests/test_state_clear' => 'tests#test_state_clear', via: [:post]
  match 'tests/save_score' => 'tests#save_score', via: [:post]
  
  get 'api' => 'api#index'
  get 'api/sparql/:format' => 'api#sparql'
  get 'api/:selector/:format' => 'api#predefined'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         #:recoverable,
         :rememberable, :trackable, :validatable,
         authentication_keys: [:login]
       
  belongs_to :role
  has_one :test_state, dependent: :destroy
  has_many :test_results, dependent: :destroy
  has_many :selections, dependent: :destroy
  
  validates :username, uniqueness: {case_sensitive: false}
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def profile
    repository = Sparql::Repository::UsersRepository.new
    
    @test_results = current_user.test_results.order(created_at: :desc)
    @selections = current_user.selections.order(created_at: :desc)
    @triples = repository.get_selections
  end
  
  def save_selections
    ActiveRecord::Base.transaction do
      params['selections'].each do |key, val|
        selection = Selection.find_by_id(Integer(val['id']))
        if selection
          if val['_destroy']
            selection.destroy 
          else
            selection.name = val['name']
            selection.save
          end
        end
      end
    end
    
    render json: {'status' => 'ok'}
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="site-heading"><%= t 'users.heading.profile' %></h3>
  </div>
  <div class="panel-body">
    <div>
      <%# BEGIN SCORE %>
      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="body-section-heading no-margin-top"><%= t 'users.heading.test_results' %></h3>
            <% for test_result in @test_results
                 percentage = 100 * Float(test_result.score) / Float(test_result.total)
                 if percentage < 35
                   performance_class = 'alert-danger'
                 elsif percentage < 70
                  performance_class = 'alert-warning'
                 else
                   performance_class = 'alert-success'
                 end
            %>
              <div class="alert <%= performance_class %> alert-data">
                <%= t 'users.label.score' %>: <span class="score-scored"><%= test_result.score %></span> / <span class="score-total"><%= test_result.total %></span>
                <span class="pull-right">(<%= test_result.created_at %>)</span>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <%# END SCORE %>
      
      <%# BEGIN SELECTIONS %>
      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="body-section-heading no-margin-top">
              <%= t 'users.heading.saved_selections' %>
              <button id="save_selections" data-bind="click: save" class="btn btn-default pull-right" style="margin-top: -6px;" type="button"><%= t 'users.btn.save_changes' %></button>
            </h3>
            <div id="selections-accordion" class="panel-group" data-bind="foreach: selections">
              <%# for selection in current_user.selections -%>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <a data-bind="text: name, attr: {'href': '#collapse_' + id}" data-toggle="collapse" data-parent="#selections-accordion"></a>
                      <input data-bind="value: name" class="form-control edit-control" style="display: none;">
                      <span class="glyphicon glyphicon-list-alt glyphicon-selection-options list-words" title="<%= t 'users.label.list_words' %>" style="margin-left: 8px;"></span>
                      <form action="<%= words_path %>" class="list-words-form" method="post" style="display: none;">
                        <input data-bind="value: ko.toJSON({categorySelections: categorySelections, wordSelections: wordSelections})" name="selections" type="hidden">
                      </form>
                      <span class="glyphicon glyphicon-edit glyphicon-selection-options edit" title="<%= t 'users.label.edit_name' %>"></span>
                      <span data-bind="click: $parent.destroySelection" class="glyphicon glyphicon-remove glyphicon-selection-options remove" title="<%= t 'users.label.remove' %>"></span>
                      <span class="pull-right" data-bind="text: createdAt"></span>
                    </h4>
                  </div>
                  <div data-bind="attr: {'id': 'collapse_' + id}" class="panel-collapse collapse out">
                    <div class="panel-body">
                      <dl class="dl-horizontal dl-selection">
                        <!-- ko if: categorySelections.length > 0 -->
                        <dt><%= t 'users.label.category_selections' %>:</dt>
                        <dd>
                          <ul data-bind="foreach: categorySelections" class="list-unstyled list-inline list-comma-separated">
                            <li data-bind="attr: {'about': categoryRdf}">
                              <span data-bind="text: category" property="rdfs:label" lang="de"></span>
                            </li>
                          </ul>
                        </dd>
                        <!-- /ko -->
                        <!-- ko if: wordSelections.length > 0 -->
                        <dt><%= t 'users.label.word_selections' %>:</dt>
                        <dd>
                          <ul data-bind="foreach: wordSelections" class="list-unstyled list-inline list-comma-separated">
                            <li data-bind="attr: {'about': wordRdf}">
                              <span data-bind="text: word" property="rdfs:label" lang="de"></span>
                            </li>
                          </ul>
                        </dd>
                        <!-- /ko -->
                      </dl>
                    </div>
                  </div>
                </div>
              <%# end -%>
            </div>
          </div>
        </div>
      </div>
      <%# END SELECTIONS %>
    </div>
  </div>
</div>

<script type="text/javascript">
  jQuery(function($) {
    // show tooltips
    $('.edit, .remove, .list-words').tooltip({
      delay: {show: 500, hide: 0}
    });
    
    // hiding / showing editors
    $('.glyphicon-selection-options.edit').click(function() {
      // show edit input
      $(this).parent('.panel-title').find('[data-bind="value: name"]').first().css('display', 'inline-block').focus();
      $(this).parent('.panel-title').find('[data-bind^="text: name"]').first().hide();
    });

    // edit selection name
    $('.edit-control').keydown(function(e) {
      if (13 === e.keyCode) {
        $(this).hide();
        $(this).parent('.panel-title').find('[data-bind^="text: name"]').first().show();
      }
    });
  });
  
  // disable 'save selections' button
  $('#save_selections').attr('disabled', true);
  
  // enable 'save selections' button after clicking on 'edit' or 'remove' button
  $(document).on('click', '.edit, .remove', function() {
      $('#save_selections').attr('disabled', false);
  });
  
  // list words
  $(document).on('click', '.list-words', function() {
    $(this).parent().find('.list-words-form').submit();
  });
  
  // ko models
  function CategorySelection(data) {
    this.category = data.category;
    this.categoryRdf = data.categoryRdf;
  }

  function WordSelection(data) {
    this.word = data.word;
    this.wordRdf = data.wordRdf;
  }
  
  function Selection(data) {
    this.id = data.id;
    this.name = ko.observable(data.name);
    this.createdAt = data.createdAt;
    this.categorySelections = data.categorySelections;
    this.wordSelections = data.wordSelections;
  }
  
  // ko selections viewmodel
  function SelectionsViewModel() {
    var self = this;
    
    self.selections = ko.observableArray([
      <% for selection in @selections -%>
        new Selection({
          id: <%= selection.id %>,
          name: '<%= selection.name %>',
          createdAt: '<%= selection.created_at %>',
          categorySelections: [
            <% for category_selection in selection.category_selections -%>
              new CategorySelection({
                category: '<%= @triples[category_selection.category][RDF::Prefixes::RDFS+'label'][I18n.locale.to_s.upcase] %>',
                categoryRdf: '<%= category_selection.category %>'
              }),
            <% end -%>
          ],
          wordSelections: [
            <% for word_selection in selection.word_selections -%>
              new WordSelection({
                word: '<%= @triples[word_selection.word][RDF::Prefixes::RDFS+'label']['DE'] %>',
                wordRdf: '<%= word_selection.word %>'
              }),
            <% end -%>
          ]
        }),
      <% end -%>
    ]);
    
    self.destroySelection = function(selection) {
      bootbox.confirm('<%= t 'users.message.confirm_selection_remove' %>', function(result) {
        if (result) self.selections.destroy(selection);
      });
    };
    self.removeSelection = function(selection) { self.selections.remove(selection) };
    self.save = function() {
      var jsonString = ko.toJSON(self);
      $.post('<%= users_save_selections_path %>', JSON.parse(jsonString), function() {
        $('#save_selections').attr('disabled', true).notify('<%= t 'users.message.selections_save_success' %>', 'success');
      })
      .fail(function() {
        $('#save_selections').notify('<%= t 'users.message.selections_save_error' %>', 'error');
      });
    };
  }
  
  ko.applyBindings(new SelectionsViewModel());
</script>