config/routes.rb
Voc::Application.routes.draw do
  
  devise_for :users
  get 'users/profile' => 'users#profile'
  match 'users/save_selections' => 'users#save_selections', via: [:post]

  root 'words#index'

  
  match 'words' => 'words#index', via: [:get, :post]
  match 'words/save_selection' => 'words#save_selection', via: [:post]
  
  match 'tests' => 'tests#index', via: [:post]
  match 'tests/autosave' => 'tests#autosave', via: [:post]
  get 'tests/autoload' => 'tests#autoload'
  match 'tests/test_state_clear' => 'tests#test_state_clear', via: [:post]
  match 'tests/save_score' => 'tests#save_score', via: [:post]
  
  get 'api' => 'api#index'
  get 'api/sparql/:format' => 'api#sparql'
  get 'api/:selector/:format' => 'api#predefined'

  

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  protect_from_forgery except: [:index]
  before_filter :authenticate_user!, only: [:save_selection]
  
  def index
    # initialize repository
    repository = Sparql::Repository::WordsRepository.new
    
    # get kb data
    @words_display = repository.get_words_display
    @words = repository.get_words
    @categories = repository.get_categories
    @category_associations = repository.get_category_associations
    
    # assign words to columns
    @col_count = 3
    col_size = @words_display.length / @col_count
    col_size, @col_count = 1, @words_display.length if 0 == col_size
    @col = Array.new
    
    @col_count.times do |i|
      @col[i] = Hash.new
    end
    
    i = 0
    @words_display.each do |key, val|
      col_index = i / col_size;
      col_index -= 1 if col_index > @col_count - 1;
      @col[col_index][key] = val
      i += 1
    end
    
    # parse selections
    if params['selections']
      @selections = JSON.parse(params['selections'])
    end
  end
  
  def save_selection
    raise Exception.new('No words or categories selected.') unless params['word_selections'] || params['category_selections']
    
    selection = Selection.new(name: 'selection', user: current_user)
    selection.save
    if params['word_selections']
      params['word_selections'].each {|word_selection| selection.word_selections.create(word: word_selection[1]['word'])}
    end
    if params['category_selections']
      params['category_selections'].each {|category_selection| selection.category_selections.create(category: category_selection[1]['category'])}
    end
    
    render json: {'status' => 'ok'}
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/index.html.erb
<% has_association_predicate = 'http://semvoc.net/voc#hasAssociation' %>
<% is_of_advancement_level_predicate = 'http://semvoc.net/voc#isOfAdvancementLevel' %>
<% label_predicate = 'http://www.w3.org/2000/01/rdf-schema#label' %>
<div class="box-side">
  <div class="panel panel-default box-side-content">
    <div class="panel-body">
      <ul class="list-unstyled no-margin-bottom">
        <li><span class="clickable generate-test"><%= t 'words.label.generate_test' %></span></li>
        <% if user_signed_in? -%>
          <li><span class="clickable save-selection"><%= t 'words.label.save_selection' %></span></li>
        <% end -%>
      </ul>
    </div>
  </div>
  <div class="btn btn-warning box-side-icon">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="col-lg-2 col-categories">
      <h3 class="label-categories">
        <%= t 'words.label.categories' %>
        <span class="glyphicon glyphicon-collapse-down collapse-categories" data-toggle="collapse" data-target="#categories"></span>
      </h3>
    </div>
    <div class="col-lg-10">
      <div id="categories" class="collapse">
        <ul class="list-inline list-categories">
          <% @categories.each do |s, o| %>
            <li about="<%= s['value'] %>">
              <span property="rdfs:label" content="<%= o['value'] %>">
                <%= o['value'] %>
              </span>
            </li>
          <% end %>
        </ul>
      </div>
      <button id="apply_filter" type="button" class="btn btn-sm btn-default"><%= t 'words.label.apply_filter' %></button>
      <button id="clear_filter" type="button" class="btn btn-sm btn-default"><%= t 'words.label.clear_filter' %></button>
    </div>
  </div>
</div>
<% @col.each_with_index do |val, col_index| %>
  <div class="col-lg-4 col-words <%= 'col-last' if col_index == @col_count - 1 %>">
    <div class="panel panel-default">
      <div class="panel-body">
        <ul class="list-unstyled">
          <%
          @col[col_index].each do |key, val|
            if @words[key] 
              content = '<dl class="dl-horizontal dl-align-left">'
              @words[key].each do |p, arr|
                unless has_association_predicate == p['value']
                  arr.each do |v|
                    unless (label_predicate == p['value'] && v['o']['xml:lang'] != I18n.locale.to_s.upcase) || (is_of_advancement_level_predicate == p['value'] && v['l']['xml:lang'] != I18n.locale.to_s.upcase)
                      o = (v['l'] ? v['l'] : v['o'])
                      content += "<dt>#{p['value'].split('#')[1]}</dt><dd>#{o['value']}</dd>"
                    end
                  end
                end
              end
              content += '</dl>'
              %>
              <li>
                <div
                  class="word-item"
                  data-html="true"
                  data-content="<%= content %>"
                  data-trigger="hover"
                  data-toggle="popover"
                  about="<%= key['value'] %>"
                  >
                  <%# Print word %>
                  <span class="word-label"><%= val %></span>
                  <%# Print word's RDFa triples %>
                  <div class="rdfa-properties hidden">
                  <% @words[key].each do |p, arr|
                    unless has_association_predicate == p['value']
                      arr.each do |v|
                        unless (label_predicate == p['value'] && v['o']['xml:lang'] != I18n.locale.to_s.upcase) || (is_of_advancement_level_predicate == p['value'] && v['l']['xml:lang'] != I18n.locale.to_s.upcase)
                        %>
                          <span
                            property="<%= p['value'] %>"
                            content="<%= v['o']['value'] %>"
                            <% if v['o']['xml:lang'] %>
                            lang="<%= v['o']['xml:lang'] %>"
                            <% end %>
                            >
                            <%= v['o']['value'] %>
                          </span>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% end %>
                  <%# Print word's RDFa category association triples %>
                  <% if @category_associations[key] %>
                    <% @category_associations[key].each do |a, h| %>
                      <span rel="voc:hasAssociation" resource="<%= a['value'] %>">
                        <span property="voc:associationValue" content="<%= h['v']['value'] %>"><%= h['v']['value'] %></span>
                        <span property="voc:associationWeight" content="<%= h['w']['value'] %>"><%= h['w']['value'] %></span>
                      </span>
                    <% end %>
                  <% end %>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
$(function() {
  // words popover
  $('[data-toggle="popover"]').popover();

  //filter
  //
  //
  // collapse categories
  $('.collapse-categories').collapse();
  // toggle glyphicon
  $('.collapse-categories').click(function() {
    if ($(this).hasClass('glyphicon-collapse-down')) {
      $(this).removeClass('glyphicon-collapse-down').addClass('glyphicon-collapse-up');
    } else {
      $(this).removeClass('glyphicon-collapse-up').addClass('glyphicon-collapse-down');
    }
  });
  
  // filter functions
  var isHighlighted = function($object) {
    return $object.hasClass('label') && $object.hasClass('label-warning');
  };
  
  var highlight = function($object) {
    if (!isHighlighted($object)) $object.addClass('label').addClass('label-warning');
  };
  
  var unhighlight = function($object) {
    if (isHighlighted($object)) $object.removeClass('label').removeClass('label-warning');
  };
  
  var getSelectedAssociations = function() {
    var associations = {};
    $('#categories li').each(function() {
      if (isHighlighted($(this).find('[property="rdfs:label"]').first())) {
        associations[$(this).attr('about')] = 1;
      }
    });
    $('.word-item').each(function() {
      var $wordLabel = $(this).find('.word-label').first();
      if (isHighlighted($wordLabel)) {
        $(this).find('[rel="voc:hasAssociation"]').each(function() {
          var category = $(this).find('[property="voc:associationValue"]').first().attr('content');
          var weight = parseFloat($(this).find('[property="voc:associationWeight"]').first().attr('content'));
          if (!associations[category] || associations[category] < weight) {
            associations[category] = weight;
          }
        });
      }
    });
    return associations;
  };
  
  var displayAssociations = function(associations) {
    $('.word-item').each(function() {
      var $wordLabel = $(this).find('.word-label').first();
      var show = false;
      var fitness = 0;
      
      $(this).find('.rdfa-properties [rel="voc:hasAssociation"]').each(function() {
        var category = $(this).find('[property="voc:associationValue"]').first().attr('content');
        var weight = parseFloat($(this).find('[property="voc:associationWeight"]').first().attr('content'));
        if (associations[category]) {
          show = true;
          if (weight * associations[category] > fitness) fitness = weight * associations[category];
        }
      });
      if (show) {
        $wordLabel.css('color', weightedColor(fitness));
        $(this).show();
      } else {
        $(this).hide();
      }
    });
  };
  
  // apply filter
  $('#apply_filter').click(function() {
    var associations = getSelectedAssociations();
    if ($.isEmptyObject(associations)) {
      bootbox.alert('<%= t 'words.message.no_selection' %>');
      return;
    }
    displayAssociations(associations);
  });
  
  // clear filter
  $('#clear_filter').click(function() {
    $('.list-categories li span').each(function() {
      unhighlight($(this));
    });
    $('.word-label').each(function() {
      unhighlight($(this));
      $(this).css('color', weightedColor(1.0));
      $(this).parent('.word-item').show();
    });
  });
  
  <% if defined? @selections -%>
    <% if @selections['categorySelections'] -%>
      // load category selections from post data
      var categorySelections = [
        <% for category_selection in @selections['categorySelections'] -%>
            '<%= category_selection['categoryRdf'] %>',
        <% end -%>
      ];
      
      categorySelections.forEach(function(categoryRdf) {
        highlight($('[about="' + categoryRdf + '"] [property="rdfs:label"]'));
      });
    <% end -%>

    <% if @selections['categorySelections'] -%>
      // load word selections from post data
      var wordSelections = [
        <% for word_selection in @selections['wordSelections'] -%>
            '<%= word_selection['wordRdf'] %>',
        <% end -%>
      ];
      
      wordSelections.forEach(function(wordRdf) {
        highlight($('[about="' + wordRdf + '"] .word-label'));
      });
    <% end -%>
      
    displayAssociations(getSelectedAssociations());
  <% end -%>
  
  // side box
  var contentWidth = $('.box-side-content').width();
  $('.box-side').css('left', -contentWidth - 1 + 'px');
  
  $('.box-side-icon').click(function() {
    var translationLength = $('.box-side-content').width();
    var $span = $(this).find('span').first();
    if ($span.hasClass('glyphicon-chevron-right')) {
      $('.box-side').transition({x: translationLength + 'px'});
      $span.removeClass('glyphicon-chevron-right').addClass('glyphicon-chevron-left');
    } else {
      $('.box-side').transition({x: 0});
      $span.removeClass('glyphicon-chevron-left').addClass('glyphicon-chevron-right');
    }
  });
  
  // highlight words and categories
  $('.word-label, .list-categories li [property="rdfs:label"]').click(function() {
    if (isHighlighted($(this))) {
      unhighlight($(this));
    } else {
      highlight($(this));
    }
  });
  
  var getWordsRandom = function() {
    var result = [];
    $('.word-item').each(function() {
      result.push($(this).attr('about'));
    });
    return _.shuffle(result);
  };
  
  // generate test
  $('.generate-test').click(function() {
    var limit = 20;
    var associations = getSelectedAssociations();
    var wordsRandom = getWordsRandom();
    var words = [];
    var i = 0;
    wordsRandom.every(function(element) {
      if (limit === i) return false;
      $('[about="' + element + '"] [rel="voc:hasAssociation"]').each(function() {
        var category = $(this).find('[property="voc:associationValue"]').first().attr('content');
        var weight = parseFloat($(this).find('[property="voc:associationWeight"]').first().attr('content'));
        if (associations[category] && (weight * associations[category] > Math.random())) {
          words.push(element);
          i++;
          return false;
        }
      });
      return true;
    });
    
    if (words.length > 0) {
      var postParams = {};
      postParams['words'] = [];
      _.each(words, function(element) {
        postParams['words'].push(element);
      });

      post_to_url('<%= tests_path %>', postParams);
    } else {
      bootbox.alert('<%= t 'words.message.no_selection' %>');
    }
  });
  
  <% if user_signed_in? -%>
  // save selection
  $('.save-selection').click(function() {
    var word_selections = [];
    var category_selections = [];
    
    $('.word-item').each(function() {
      if (isHighlighted($(this).find('.word-label').first())) {
        word_selections.push({word: $(this).attr('about')});
      }
    });
    $('#categories li').each(function() {
      if (isHighlighted($(this).find('[property="rdfs:label"]').first())) {
        category_selections.push({category: $(this).attr('about')});
      }
    });
    
    if (word_selections.length > 0 || category_selections.length > 0) {
      $.post('<%= words_save_selection_path %>', {
        word_selections: word_selections,
        category_selections: category_selections
      }, function() {
        bootbox.alert('<%= t 'words.message.selection_saved' %>');
      })
      .fail(function(data) {
        bootbox.alert('<%= t 'words.message.selection_save_failed' %>');
      });
    } else {
      bootbox.alert('<%= t 'words.message.no_selection' %>');
    }
  });
  <% end -%>
});
</script>