config/routes.rb
Voc::Application.routes.draw do
  
  devise_for :users
  get 'users/profile' => 'users#profile'
  match 'users/save_selections' => 'users#save_selections', via: [:post]

  root 'words#index'

  
  match 'words' => 'words#index', via: [:get, :post]
  match 'words/save_selection' => 'words#save_selection', via: [:post]
  
  match 'tests' => 'tests#index', via: [:post]
  match 'tests/autosave' => 'tests#autosave', via: [:post]
  get 'tests/autoload' => 'tests#autoload'
  match 'tests/test_state_clear' => 'tests#test_state_clear', via: [:post]
  match 'tests/save_score' => 'tests#save_score', via: [:post]
  
  get 'api' => 'api#index'
  get 'api/sparql/:format' => 'api#sparql'
  get 'api/:selector/:format' => 'api#predefined'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
  xmlns:voc="http://semvoc.net/voc#"
  xmlns:semvoc="http://semvoc.net/semvoc#"
  lang="<%= I18n.locale %>">
  <head>
    <title>Semvoc</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Semvoc', words_path, {class: 'navbar-brand'} %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to t('label.words_path'), words_path  %> </li>
          <li><%= link_to t('label.api_path'), api_path  %> </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= t 'label.user_options' %> (<%= current_user.username %>) <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t('label.profile'), users_profile_path %></li>
                <li><%= link_to t('label.edit'), edit_user_registration_path %><hr class="small-spacing"></li>
                <% if current_user.test_state && 'tests' != params[:controller] -%>
                  <li><%= link_to t('label.back_test'), tests_autoload_path %><hr class="small-spacing"></li>
                <% end -%>
                <li><%= link_to t('label.sign_out'), destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t('label.sign_in'), new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div role="main" class="container">
      <div class="row navbar-clear">
      </div>
      <div class="row">
        <% if alert %>
          <div class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= alert %>
          </div>
        <% end %>
        <% if notice %>
          <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= notice %>
          </div>
        <% end %>
        <%= yield %>
      </div>
      <footer>
        <div class="panel panel-default">
          <div class="panel-body">
            &copy; Semvoc.net
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>